
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdci-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - cdci-network
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: cdci-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cdci-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: cdci-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3311:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cdci-network

networks:
  cdci-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local